version: "2"
linters:
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - exhaustive
    - exhaustruct
    - goconst
    - gocritic
    - gosec
    - nilnil
    - revive
    - unused
  exclusions:
    presets:
      - comments
  settings:
    exhaustruct:
      exclude:
        - 'github.com\/rs\/zerolog\..*'
        - 'github.com\/urfave\/cli\/v3\..*'
      allow-empty: true
    unused:
      field-writes-are-uses: false
      exported-fields-are-used: false
      local-variables-are-used: false
